<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.prettyPhoto.js"></script>
<script src="js/main.js"></script>
<script src="js/reloj.js"></script>
<script src="dataTable/js/jquery.dataTables.js" ></script>
<script src="dataTable/js/jquery.dataTables.min.js" ></script>
<script src="js/jquery.validate.js"></script>
<script src="webcodecamjs-master/js/qrcodelib.js"></script>
<script src="webcodecamjs-master/js/webcodecamjquery.js"></script>
<script src="webcodecamjs-master/js/mainjquery.js"></script>